name: Docker Image CI

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/ut99-server
          IMAGE_TAG=$(echo "${GITHUB_REF_NAME}" | tr '/' '-' | tr -cd 'a-zA-Z0-9_.-')-$(echo $GITHUB_SHA | cut -c1-7)-${GITHUB_RUN_NUMBER}
          docker build -f Dockerfile -t $IMAGE_NAME:$IMAGE_TAG --no-cache .
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker logout
